In [17]:
import numpy as np

In [18]:
x = np.array([1.0, 2.0, 3.0])

In [19]:
print(x)

[1. 2. 3.]


In [20]:
type(x)
print(type(x))

<class 'numpy.ndarray'>


In [21]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])
x + y

array([3., 6., 9.])

In [22]:
x - y

array([-1., -2., -3.])

In [24]:
x * y

array([ 2.,  8., 18.])

In [25]:
x / y

array([0.5, 0.5, 0.5])

In [26]:
x = np.array([1.0, 2.0, 3.0])
x / 2.0

array([0.5, 1. , 1.5])

In [27]:
A = np.array([[1, 2], [3, 4]])
print(A)

[[1 2]
 [3 4]]


In [29]:
A.shape

(2, 2)

In [30]:
A.dtype

dtype('int64')

In [31]:
B = np.array([[3, 0], [0, 6]])

In [32]:
A + B

array([[ 4,  2],
       [ 3, 10]])

In [33]:
A * B

array([[ 3,  0],
       [ 0, 24]])

In [34]:
print(A)

[[1 2]
 [3 4]]


In [35]:
A * 10

array([[10, 20],
       [30, 40]])

In [37]:
A = np.array([[1, 2], [3, 4]])
B = np.array([10, 20])
A * B

array([[10, 40],
       [30, 80]])

In [39]:
X = np.array([[51, 55], [14, 19], [0, 4]])
print(X)

[[51 55]
 [14 19]
 [ 0  4]]


In [41]:
X[0]

array([51, 55])

In [43]:
X[0][1]
print(X[0, 1])

55


In [45]:
for row in X:
    print(row)

[51 55]
[14 19]
[0 4]


In [46]:
X = X.flatten()
print(X)

[51 55 14 19  0  4]


In [47]:
X[np.array([0, 2, 4])]

array([51, 14,  0])

In [50]:
X > 15

array([ True,  True, False,  True, False, False])

In [51]:
X[X > 15]

array([51, 55, 19])