In [9]:
import numpy as np


def step_function(x):
    if x > 0:
        return 1
    else:
        return 0


def step_function(x):
    y = x > 0
    return y.astype(int)

In [10]:
x = np.array([-1.0, 1.0, 2.0])
x

array([-1.,  1.,  2.])

In [11]:
y = x > 0
y

array([False,  True,  True])

In [12]:
y = y.astype(int)
y

array([0, 1, 1])